//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestWeb.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @using TestWeb;
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;input id=&quot;auth-password&quot; type=&quot;password&quot; placeholder=&quot;@Views.WEB_Auth_Password&quot; name=&quot;pass&quot;&gt;
        ///    @if (Session != null)
        ///    {
        ///        &lt;h1&gt;Привет @Session.Data.Login&lt;/h1&gt;
        ///        &lt;h2&gt;&lt;a href=&quot;/auth/logout&quot;&gt;Выход&lt;/a&gt;&lt;/h2&gt;
        ///    }
        ///    else
        ///    {
        ///        &lt;h1&gt;&lt;a href=&quot;/auth/login&quot;&gt;Залогинься!&lt;/a&gt;&lt;/h1&gt;
        ///    }
        ///
        ///    &lt;p&gt;Now is @DateTime.Now&lt;/p&gt;
        ///    &lt;img src=&quot;/logo_primary.svg&quot;&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @import url(imports/jquery-ui.min.css);
        ///@import url(imports/bootstrap.min.css);
        ///@import url(imports/bootstrap-datetimepicker.min.css);
        ///.ui-widget {
        ///  font-size: 1.1em; }
        ///
        ///.ui-widget .ui-widget {
        ///  font-size: 1em; }
        ///
        ///.ui-widget input,
        ///.ui-widget select,
        ///.ui-widget textarea,
        ///.ui-widget button {
        ///  font-size: 1em; }
        ///
        ///.ui-widget-content {
        ///  border: 0 none;
        ///  background-color: #ffffff;
        ///  color: #222222; }
        ///
        ///.ui-widget-content a {
        ///  color: #222222; }
        ///
        ///.ui-dialog-titlebar {
        ///  font-weight: 500 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string main_css {
            get {
                return ResourceManager.GetString("main_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на asdfg.
        /// </summary>
        public static string WEB_Auth_Password {
            get {
                return ResourceManager.GetString("WEB_Auth_Password", resourceCulture);
            }
        }
    }
}
